### ISSUE TITLE
[Instance][Halls of Stone] Shatter affecting Pets

### ISSUE THREAD

**Issue by whitestar87** [SunwellTracker/issues#323]
Decription: 
The debuff shatter is stacking on pets (warlock pets, hunter pets, mirror images).

How it works: 
Pets are getting shattered and causing immense AoE damage to players around them.

How it should work: 
Pets should be immune to the shatter debuff.

Source (you should point out proofs of your report, please give us some source):

**Comment by Netherfrost** [comment]
Totems, blood worms, anything really.

**Comment by Kokaina** [comment]
Fixed.

**Comment by BjarkiFreyr95** [comment]
Not fixed, I just recently (2-3 hours ago) died because the shatter affected my bloodworms. I cannot deactivate them so I have to use my dps spec (unholy).
