### ISSUE TITLE
Cache of the Ley-Guardian in Oculus

### ISSUE THREAD

**Issue by artemmavrich** [SunwellTracker/issues#815]
Decription: 
[Cache of the Ley-Guardian](https://db.darkwizard.pl/?item=52676) must be a random reward from the last boss in Oculus. I just got this bag doing EXACT Oculus (ticked this dungeon in dungeon finder). This bug makes gems from this bag cost lower if it drops NOT in RANDOM dungeon finder

How it works: 
[Cache of the Ley-Guardian](https://db.darkwizard.pl/?item=52676) must be a random reward from the last boss in Oculus. I just got this bag doing EXACT Oculus (ticked this dungeon in dungeon finder). This bug makes gems from this bag cost lower if it drops NOT in RANDOM dungeon finder

How it should work: 

Source (you should point out proofs of your report, please give us some source):

**Comment by Riztazz** [comment]
Should be resolved with next update.

**Comment by artemmavrich** [comment]
Still not working properly. I still can get it not using RANDOM dungeon finder.

**Comment by Riztazz** [comment]
Yeah, fix was reverted, i know about that one and will push another fix next week
